services:
  backend:
    build:
      context: ./taskmanager
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    env_file:
      - ./.env 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./taskmanager/prisma:/app/prisma
    networks:
      - fullstack_network

  frontend:
    build:
      context: ./nexttask
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://${DOCKER_HOST_IP}:${BACKEND_PORT:-3000} 
    container_name: nexttask-frontend
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - ./.env 
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://${DOCKER_HOST_IP}:${BACKEND_PORT:-3000}
    depends_on:
      - backend

    networks:
          - fullstack_network


networks:
  fullstack_network:
    external: false